// <auto-generated />
using System;
using DigiPOSE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigiPOSE.Migrations
{
    [DbContext(typeof(DigiPoseDbContext))]
    [Migration("20260723090808_Convert_To_Explicit_PermissionRole")]
    partial class Convert_To_Explicit_PermissionRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigiPOSE.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BranchId");

                    b.HasIndex("BranchName")
                        .IsUnique();

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("DigiPOSE.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Electronics",
                            Description = "Electronic devices and accessories",
                            IsActive = true,
                            Slug = "electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Home Appliances",
                            Description = "Appliances for home use",
                            IsActive = true,
                            Slug = "home-appliances"
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.Counter", b =>
                {
                    b.Property<int>("CounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CounterId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CounterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CounterId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CounterName")
                        .IsUnique();

                    b.ToTable("Counters", (string)null);
                });

            modelBuilder.Entity("DigiPOSE.Models.CustomeType", b =>
                {
                    b.Property<int>("CustomeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomeTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomeTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("CustomerTypes", (string)null);

                    b.HasData(
                        new
                        {
                            CustomeTypeId = 1,
                            Description = "Standard one-time buyers",
                            TypeName = "Walk-in Customer"
                        },
                        new
                        {
                            CustomeTypeId = 2,
                            Description = "Loyal customers with membership benefits",
                            TypeName = "VIP Member"
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BudgetCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CustomeTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("DebtBalance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomeTypeId");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("TaxCode");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("DigiPOSE.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InvoiceLookupCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("InvoiceStatusId")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("OriginInvoiceReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OriginalInvoiceNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaxAuthorityCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("InvoiceStatusId");

                    b.HasIndex("InvoiceTypeId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("DigiPOSE.Models.InvoiceStatus", b =>
                {
                    b.Property<int>("InvoiceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceStatusId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InvoiceStatusId");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("InvoiceStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            InvoiceStatusId = 1,
                            Description = "Fully paid invoice",
                            StatusName = "Paid"
                        },
                        new
                        {
                            InvoiceStatusId = 2,
                            Description = "Payment pending",
                            StatusName = "Unpaid"
                        },
                        new
                        {
                            InvoiceStatusId = 3,
                            Description = "Canceled invoice",
                            StatusName = "Void"
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.InvoiceType", b =>
                {
                    b.Property<int>("InvoiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("InvoiceTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("InvoiceTypes", (string)null);

                    b.HasData(
                        new
                        {
                            InvoiceTypeId = 1,
                            Description = "Standard POS checkout",
                            TypeName = "Standard Sale"
                        },
                        new
                        {
                            InvoiceTypeId = 2,
                            Description = "Customer return invoice",
                            TypeName = "Return"
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.ItemNature", b =>
                {
                    b.Property<int>("NatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NatureId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaxXmlCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NatureId");

                    b.HasIndex("NatureName")
                        .IsUnique();

                    b.ToTable("ItemNatures", (string)null);

                    b.HasData(
                        new
                        {
                            NatureId = 1,
                            IsActive = true,
                            NatureName = "Physical Goods",
                            TaxXmlCode = "1"
                        },
                        new
                        {
                            NatureId = 2,
                            IsActive = true,
                            NatureName = "Digital Service",
                            TaxXmlCode = "2"
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Website")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ManufacturerId");

                    b.HasIndex("ManufacturerName")
                        .IsUnique();

                    b.ToTable("Manufacturers", (string)null);

                    b.HasData(
                        new
                        {
                            ManufacturerId = 1,
                            Description = "Sony Electronics Corporation",
                            IsActive = true,
                            ManufacturerName = "Sony",
                            Slug = "sony"
                        },
                        new
                        {
                            ManufacturerId = 2,
                            Description = "Samsung Electronics",
                            IsActive = true,
                            ManufacturerName = "Samsung",
                            Slug = "samsung"
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DiscountReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("OrderStatusStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotCustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SnapshotCustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("OrderId"), false);

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderStatusStatusId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId");

                    b.HasIndex("BranchId", "CreatedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("BranchId", "CreatedAt"));

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("DigiPOSE.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<int?>("ItemNatureNatureId")
                        .HasColumnType("int");

                    b.Property<int>("NatureId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TaxTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("ItemNatureNatureId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TaxTypeId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("DigiPOSE.Models.OrderStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("BadgeColor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("OrderStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Description = "Order finalized and delivered",
                            StatusName = "Completed"
                        },
                        new
                        {
                            StatusId = 2,
                            Description = "Order awaiting payment",
                            StatusName = "Pending"
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentMethodId");

                    b.HasIndex("MethodName")
                        .IsUnique();

                    b.ToTable("PaymentMethods", (string)null);

                    b.HasData(
                        new
                        {
                            PaymentMethodId = 1,
                            Description = "Cash payment at counter",
                            MethodName = "Cash"
                        },
                        new
                        {
                            PaymentMethodId = 2,
                            Description = "Visa/Mastercard",
                            MethodName = "Credit Card"
                        },
                        new
                        {
                            PaymentMethodId = 3,
                            Description = "Momo, ZaloPay, etc.",
                            MethodName = "E-Wallet"
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SystemModuleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.HasIndex("SystemModuleId");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            Description = "Manage global system configurations and settings.",
                            PermissionName = "System.Config.Manage",
                            SystemModuleId = 1
                        },
                        new
                        {
                            PermissionId = 2,
                            Description = "Create, edit, and delete branches and counters.",
                            PermissionName = "System.Branch.Manage",
                            SystemModuleId = 1
                        },
                        new
                        {
                            PermissionId = 3,
                            Description = "Create, edit, and delete user roles and permissions.",
                            PermissionName = "System.Role.Manage",
                            SystemModuleId = 1
                        },
                        new
                        {
                            PermissionId = 4,
                            Description = "Manage user accounts, reset passwords, and assign roles.",
                            PermissionName = "System.User.Manage",
                            SystemModuleId = 1
                        },
                        new
                        {
                            PermissionId = 5,
                            Description = "Open a new cashier shift and declare starting cash.",
                            PermissionName = "POS.Shift.Open",
                            SystemModuleId = 2
                        },
                        new
                        {
                            PermissionId = 6,
                            Description = "Close an active shift and declare ending cash.",
                            PermissionName = "POS.Shift.Close",
                            SystemModuleId = 2
                        },
                        new
                        {
                            PermissionId = 7,
                            Description = "Create new retail orders and process payments.",
                            PermissionName = "POS.Order.Create",
                            SystemModuleId = 2
                        },
                        new
                        {
                            PermissionId = 8,
                            Description = "Cancel or void a completed order/invoice.",
                            PermissionName = "POS.Order.Void",
                            SystemModuleId = 2
                        },
                        new
                        {
                            PermissionId = 9,
                            Description = "Apply special discounts beyond standard limits.",
                            PermissionName = "POS.Discount.Apply",
                            SystemModuleId = 2
                        },
                        new
                        {
                            PermissionId = 10,
                            Description = "View current product stock levels.",
                            PermissionName = "Warehouse.Inventory.View",
                            SystemModuleId = 3
                        },
                        new
                        {
                            PermissionId = 11,
                            Description = "Create stock-in, stock-out, or transfer vouchers.",
                            PermissionName = "Warehouse.Voucher.Create",
                            SystemModuleId = 3
                        },
                        new
                        {
                            PermissionId = 12,
                            Description = "Approve pending stock vouchers for processing.",
                            PermissionName = "Warehouse.Voucher.Approve",
                            SystemModuleId = 3
                        },
                        new
                        {
                            PermissionId = 13,
                            Description = "Adjust stock quantities after physical counting.",
                            PermissionName = "Warehouse.Inventory.Adjust",
                            SystemModuleId = 3
                        },
                        new
                        {
                            PermissionId = 14,
                            Description = "Manage supplier profiles and information.",
                            PermissionName = "Warehouse.Supplier.Manage",
                            SystemModuleId = 3
                        },
                        new
                        {
                            PermissionId = 15,
                            Description = "Create, edit, or disable product records.",
                            PermissionName = "Catalog.Product.Manage",
                            SystemModuleId = 4
                        },
                        new
                        {
                            PermissionId = 16,
                            Description = "Manage product categories, types, and units.",
                            PermissionName = "Catalog.Category.Manage",
                            SystemModuleId = 4
                        },
                        new
                        {
                            PermissionId = 17,
                            Description = "Update base prices and tax settings for products.",
                            PermissionName = "Catalog.Price.Manage",
                            SystemModuleId = 4
                        },
                        new
                        {
                            PermissionId = 18,
                            Description = "View financial dashboards and revenue reports.",
                            PermissionName = "Finance.Report.View",
                            SystemModuleId = 5
                        },
                        new
                        {
                            PermissionId = 19,
                            Description = "View and search all historical invoices and receipts.",
                            PermissionName = "Finance.Invoice.View",
                            SystemModuleId = 5
                        },
                        new
                        {
                            PermissionId = 20,
                            Description = "Export financial data and audit logs for tax purposes.",
                            PermissionName = "Finance.Audit.Export",
                            SystemModuleId = 5
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.PermissionRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("PermissionRoles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 20
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("MaxStockLevel")
                        .HasColumnType("int");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TaxTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("TaxTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("DigiPOSE.Models.ProductInventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.HasIndex("ProductId");

                    b.HasIndex("BranchId", "ProductId")
                        .IsUnique();

                    b.ToTable("ProductInventories", (string)null);
                });

            modelBuilder.Entity("DigiPOSE.Models.ProductType", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInventoryTracked")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("ProductTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ProductTypeId = 1,
                            IsActive = true,
                            IsInventoryTracked = true,
                            TypeName = "Standard Product"
                        },
                        new
                        {
                            ProductTypeId = 2,
                            IsActive = true,
                            IsInventoryTracked = false,
                            TypeName = "Bundle"
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "The person with the highest authority, managing the overall data infrastructure.",
                            RoleName = "Super Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Responsible for operations at a specific branch.",
                            RoleName = "Branch Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "The person directly at the counter to handle sales transactions.",
                            RoleName = "POS Operator"
                        },
                        new
                        {
                            RoleId = 4,
                            Description = "Responsible for managing goods, receiving/shipping/stocking.",
                            RoleName = "Warehouse"
                        },
                        new
                        {
                            RoleId = 5,
                            Description = "Personnel responsible for maintaining product information.",
                            RoleName = "Catalog"
                        },
                        new
                        {
                            RoleId = 6,
                            Description = "Controls cash flow, tax reporting, and reconciles data.",
                            RoleName = "Accountant"
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<int>("CounterId")
                        .HasColumnType("int");

                    b.Property<decimal?>("EndCash")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StartCash")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ShiftId");

                    b.HasIndex("CounterId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Shifts", (string)null);
                });

            modelBuilder.Entity("DigiPOSE.Models.ShiftStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("ShiftStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Description = "Shift is currently open",
                            StatusName = "Active"
                        },
                        new
                        {
                            StatusId = 2,
                            Description = "Shift has ended and cash declared",
                            StatusName = "Closed"
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.StockVoucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VoucherType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VoucherId");

                    b.HasIndex("BranchId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UserId");

                    b.ToTable("StockVouchers", (string)null);
                });

            modelBuilder.Entity("DigiPOSE.Models.StockVoucherDetail", b =>
                {
                    b.Property<int>("VoucherDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherDetailId"));

                    b.Property<decimal>("ActualPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("StockVoucherVoucherId")
                        .HasColumnType("int");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("VoucherDetailId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockVoucherVoucherId");

                    b.ToTable("StockVoucherDetails", (string)null);
                });

            modelBuilder.Entity("DigiPOSE.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DebtBalance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Website")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SupplierId");

                    b.HasIndex("SupplierName")
                        .IsUnique();

                    b.ToTable("Suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            DebtBalance = 0m,
                            Email = "contact@globalsupply.com",
                            IsActive = true,
                            SupplierName = "Global Supply Co."
                        },
                        new
                        {
                            SupplierId = 2,
                            DebtBalance = 0m,
                            Email = "sales@techdist.com",
                            IsActive = true,
                            SupplierName = "Tech Distributors"
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.SystemModule", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ModuleId");

                    b.ToTable("SystemModules", (string)null);

                    b.HasData(
                        new
                        {
                            ModuleId = 1,
                            Icon = "fa-solid fa-cogs",
                            IsActive = true,
                            ModuleName = "System",
                            SortOrder = 1
                        },
                        new
                        {
                            ModuleId = 2,
                            Icon = "fa-solid fa-cash-register",
                            IsActive = true,
                            ModuleName = "POS",
                            SortOrder = 2
                        },
                        new
                        {
                            ModuleId = 3,
                            Icon = "fa-solid fa-warehouse",
                            IsActive = true,
                            ModuleName = "Warehouse",
                            SortOrder = 3
                        },
                        new
                        {
                            ModuleId = 4,
                            Icon = "fa-solid fa-tags",
                            IsActive = true,
                            ModuleName = "Catalog",
                            SortOrder = 4
                        },
                        new
                        {
                            ModuleId = 5,
                            Icon = "fa-solid fa-file-invoice-dollar",
                            IsActive = true,
                            ModuleName = "Finance",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.TaxType", b =>
                {
                    b.Property<int>("TaxTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TaxXmlCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TaxTypeId");

                    b.HasIndex("TaxName")
                        .IsUnique();

                    b.ToTable("TaxTypes", (string)null);

                    b.HasData(
                        new
                        {
                            TaxTypeId = 1,
                            IsActive = true,
                            TaxName = "VAT 10%",
                            TaxPercentage = 10m,
                            TaxXmlCode = "10"
                        },
                        new
                        {
                            TaxTypeId = 2,
                            IsActive = true,
                            TaxName = "VAT 8%",
                            TaxPercentage = 8m,
                            TaxXmlCode = "8"
                        },
                        new
                        {
                            TaxTypeId = 3,
                            IsActive = true,
                            TaxName = "Tax Free",
                            TaxPercentage = 0m,
                            TaxXmlCode = "0"
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UnitId");

                    b.HasIndex("UnitName")
                        .IsUnique();

                    b.ToTable("Units", (string)null);

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            Description = "Single unit",
                            UnitName = "Piece"
                        },
                        new
                        {
                            UnitId = 2,
                            Description = "Packaged box",
                            UnitName = "Box"
                        },
                        new
                        {
                            UnitId = 3,
                            Description = "Kilogram",
                            UnitName = "Kg"
                        });
                });

            modelBuilder.Entity("DigiPOSE.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DigiPOSE.Models.Counter", b =>
                {
                    b.HasOne("DigiPOSE.Models.Branch", "Branch")
                        .WithMany("Counters")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("DigiPOSE.Models.Customer", b =>
                {
                    b.HasOne("DigiPOSE.Models.CustomeType", "CustomeType")
                        .WithMany()
                        .HasForeignKey("CustomeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomeType");
                });

            modelBuilder.Entity("DigiPOSE.Models.Invoice", b =>
                {
                    b.HasOne("DigiPOSE.Models.InvoiceStatus", "InvoiceStatus")
                        .WithMany("Invoices")
                        .HasForeignKey("InvoiceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.InvoiceType", "InvoiceType")
                        .WithMany("Invoices")
                        .HasForeignKey("InvoiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.Order", "Order")
                        .WithOne("invoice")
                        .HasForeignKey("DigiPOSE.Models.Invoice", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvoiceStatus");

                    b.Navigation("InvoiceType");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DigiPOSE.Models.Order", b =>
                {
                    b.HasOne("DigiPOSE.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigiPOSE.Models.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigiPOSE.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigiPOSE.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("OrderStatus");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigiPOSE.Models.OrderDetail", b =>
                {
                    b.HasOne("DigiPOSE.Models.ItemNature", "ItemNature")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ItemNatureNatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigiPOSE.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.TaxType", "TaxType")
                        .WithMany("OrderDetails")
                        .HasForeignKey("TaxTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemNature");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("TaxType");
                });

            modelBuilder.Entity("DigiPOSE.Models.Permission", b =>
                {
                    b.HasOne("DigiPOSE.Models.SystemModule", "Module")
                        .WithMany("Permissions")
                        .HasForeignKey("SystemModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Module");
                });

            modelBuilder.Entity("DigiPOSE.Models.PermissionRole", b =>
                {
                    b.HasOne("DigiPOSE.Models.Permission", "Permission")
                        .WithMany("PermissionRoles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.Role", "Role")
                        .WithMany("PermissionRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DigiPOSE.Models.Product", b =>
                {
                    b.HasOne("DigiPOSE.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigiPOSE.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.TaxType", "TaxType")
                        .WithMany("Products")
                        .HasForeignKey("TaxTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");

                    b.Navigation("ProductType");

                    b.Navigation("TaxType");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("DigiPOSE.Models.ProductInventory", b =>
                {
                    b.HasOne("DigiPOSE.Models.Branch", "Branch")
                        .WithMany("ProductInventories")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.Product", "Product")
                        .WithMany("ProductInventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DigiPOSE.Models.Shift", b =>
                {
                    b.HasOne("DigiPOSE.Models.Counter", "Counter")
                        .WithMany("Shifts")
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.ShiftStatus", "Status")
                        .WithMany("Shifts")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Counter");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigiPOSE.Models.StockVoucher", b =>
                {
                    b.HasOne("DigiPOSE.Models.Branch", "Branch")
                        .WithMany("StockVourchers")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.Supplier", "Supplier")
                        .WithMany("StockVouchers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigiPOSE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigiPOSE.Models.StockVoucherDetail", b =>
                {
                    b.HasOne("DigiPOSE.Models.Product", "Product")
                        .WithMany("StockVoucherDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.StockVoucher", "StockVoucher")
                        .WithMany("StockVoucherDetails")
                        .HasForeignKey("StockVoucherVoucherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("StockVoucher");
                });

            modelBuilder.Entity("DigiPOSE.Models.User", b =>
                {
                    b.HasOne("DigiPOSE.Models.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigiPOSE.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DigiPOSE.Models.Branch", b =>
                {
                    b.Navigation("Counters");

                    b.Navigation("ProductInventories");

                    b.Navigation("StockVourchers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DigiPOSE.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DigiPOSE.Models.Counter", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("DigiPOSE.Models.InvoiceStatus", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("DigiPOSE.Models.InvoiceType", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("DigiPOSE.Models.ItemNature", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("DigiPOSE.Models.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DigiPOSE.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("invoice");
                });

            modelBuilder.Entity("DigiPOSE.Models.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DigiPOSE.Models.PaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DigiPOSE.Models.Permission", b =>
                {
                    b.Navigation("PermissionRoles");
                });

            modelBuilder.Entity("DigiPOSE.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("ProductInventories");

                    b.Navigation("StockVoucherDetails");
                });

            modelBuilder.Entity("DigiPOSE.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DigiPOSE.Models.Role", b =>
                {
                    b.Navigation("PermissionRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DigiPOSE.Models.ShiftStatus", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("DigiPOSE.Models.StockVoucher", b =>
                {
                    b.Navigation("StockVoucherDetails");
                });

            modelBuilder.Entity("DigiPOSE.Models.Supplier", b =>
                {
                    b.Navigation("StockVouchers");
                });

            modelBuilder.Entity("DigiPOSE.Models.SystemModule", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("DigiPOSE.Models.TaxType", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("DigiPOSE.Models.Unit", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
